### PR TITLE
Updated Chrome and Safari Extension Development Installation

### PR DESCRIPTION
**Pull request by PoprostuRonin**
Changed URL for git repository

### CODE REVIEW

**Comment by seadog007** [comment]
I think this is not necessary, but if you want to change, can you change every clone url to same type?

**Comment by PoprostuRonin** [comment]
Done (only Safari was different).

**Comment by seadog007** [comment]
👍

**Comment by eMBee** [comment]
can you explain why you think this change is a good idea?

**Comment by PoprostuRonin** [comment]
Using newest git you just can't clone by those URLs.
reason

**Comment by seadog007** [comment]
There are some school only allow port 80 and 443, like my school :P, so I think it is a good change
And @PoprostuRonin can't use the ssh link to clone because you didn't add your ssh key into your Github account.

**Comment by smcgregor** [comment]
I'll merge this one despite misgivings about people not having a GitHub SSH key because no one will be pushing to the SSH address (except maybe, occasionally, someone that is not new to the project).

**Pull request merged**
